### ISSUE TITLE
[BUG] transfer-pvc sets ingressClassName as null

### ISSUE THREAD

**Issue by legolego621** [migtools/crane#152]
**What version of crane are you running, and what are your clutsters+platform**
crane version: v0.0.5
I use kubernetes cluster (kubeadm installed )
I have ingress-nginx controller with default ingressclass nginx
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx

```
**What actually happened?**

I try to migrate pvc from one cluster to other.
```
./crane transfer-pvc \
    --endpoint=nginx-ingress \
    --subdomain="nginx" \
    --source-context=infradoms \
    --pvc-namespace=zabbix:test \
    --pvc-name=zabbix-server-var-tmp-pvc \
    --destination-context=infradoms-test \
    --dest-storage-class=nfs-csi-fast-delete \
    --dest-storage-requests=1Gi \
    --debug \
    --verify
```

I have error

```
{"ingress":"{\"Namespace\":\"test\",\"Name\":\"zabbix-server-var-tmp-pvc\"}","level":"info","logger":"transfer-pvc","msg":"ingress class not specified, using default ingress class in the cluster","time":"2023-03-29T18:39:36+03:00"}
2023/03/29 18:39:36 Ingress.extensions "zabbix-server-var-tmp-pvc" is invalid: spec.ingressClassName: Invalid value: "": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')failed creating endpoint
```
